### ISSUE TITLE
Dynamic values in tooltip

### ISSUE THREAD

**Issue by philipbaginski** [outl1ne/nova-tooltip-field#1]
Hi!

Following sample:

use Outl1ne\NovaTooltipField\Tooltip;

public function fields(Request $request) {
    Tooltip::make('Content', 'someValue')
      ->text('Text displayed as field value')
      ->content('Content displayed in tooltip'),
}

, how to get dynamic values - text and content?

**Comment by wdelfuego** [comment]
You can implement whatever logic / text generation you need on the Eloquent model and then simply rely on `$this->resource` in order to get to it from the Nova resource.

I'm creating dynamic Tooltips like this and it works fine:

    Tooltip::make('')
        ->allowTooltipHTML()
        ->text($this->resource && $this->resource->hasUserNotes() ? '📝' : null)
        ->content($this->resource && $this->resource->hasUserNotes() 
            ? '<u>' .__("User notes") .':</u><br/>' .$this->resource->userNotes() 
            : null),

**Comment by KasparRosin** [comment]
@wdelfuego's answer is correct.
We're doing it the same way.
`$this->resource` should be available at all times.
