### ISSUE TITLE
Would it be difficult to leave the tooltip open?

### ISSUE THREAD

**Issue by wdelfuego** [outl1ne/nova-tooltip-field#2]
I would love to place links in the tooltips, but the tooltip closes automatically so they can't be clicked right now.
Would it be difficult to leave the tooltip open until a click event happens, to support this functionality?

This is not a feature request, it is an information request to estimate the complexity, I'd be happy to implement the behavior myself if you can give me an indication of its feasibility and/or pointers as to how best to go about it.

Thanks in advance!

**Comment by Tarpsvo** [comment]
Tippy seems to have a hideOnClick option. It definitely needs to be a configurable option though and tested. ;)

https://vue-tippy.netlify.app/props#hideonclick

![image](https://user-images.githubusercontent.com/2018660/225598220-e499f66c-3599-4327-868c-84daa282e59e.png)

**Comment by richard-raadi** [comment]
@wdelfuego This issue seems to have been up for a pretty while. Feel free to open a PR and we'll happily test and merge!
